### PR TITLE
Add 10x output

### PR DESCRIPTION
**Pull request by ambrosejcarr**
* added outputs
* moved inputs from 10x/ to 10x/input/

### CODE REVIEW

**Review by kbergin — APPROVED** [review]

**Comment by kbergin** [comment]
@ambrosejcarr just curious, there are 9 outputs listed in the WDL outputs section and only 6 put up here..

**Comment by ambrosejcarr** [comment]
There is some summary squashing, see conversation in humancellatlas/mintteam -- we decided to omit summary.json for the demo.

**Comment by kbergin** [comment]
Great thanks!

**Review by dshiga — CHANGES_REQUESTED** [review]
Looks good to me

**Review by dshiga — APPROVED** [review]

**Pull request merged**
